### ISSUE TITLE
Using values in an HA dashboard

### ISSUE THREAD

**Issue by mr-miles** [F1p/Home-Assistant-Mitsubishi-Ecodan-CN105-to-MQTT#15]
Thanks for a great adapter!  I have got this working nicely after some fighting with MQTT and now it is all showing up in homeassistant!

I was trying to recreate the HA dashboard in your screenshot from the repo README, is it possible for you to dump your yaml config in the docs/repo somewhere?

Specifically, I can't create the flow/return temp graph that you had, and I should preface this by saying I'm a noob at HA.

But it appears that HA needs the sensor has to have a "state_class" property set to "total" for it to be graphable in a Statistics Graph Card.  I can make it work by going to developer tools > states and adjusting the yaml - but my settings are removed/reset whenever a new value is published to mqtt.  I think the detail needs to be added into the mqtt discovery json for the sensors as "json_attributes_template" to fully "stick".

Refs:
https://community.home-assistant.io/t/mqtt-sensor-add-attributes-while-remaining-in-autodiscovery/578273/6
https://developers.home-assistant.io/docs/core/entity/sensor/#entities-not-representing-a-total-amount

Apologies if this is more of an HA question and I've missed something

**Comment by F1p** [comment]
The type shown in the screenshot is 'history graph' and the YAML is as follows:

```
type: grid
cards:
  - type: history-graph
    entities:
      - entity: sensor.ecodan_ashp_system_operation_mode
      - entity: sensor.ecodan_ashp_zone_1_working
      - entity: sensor.ecodan_ashp_zone_2_working
      - entity: sensor.ecodan_ashp_heater_flow_temperature
      - entity: sensor.ecodan_ashp_heater_return_temperature

```

Let me know if this works for you
